name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: docs
        run: npm install

      - name: Check directory structure
        working-directory: docs
        run: |
          echo "Current directory structure:"
          ls -R v/

      - name: Build with debug
        working-directory: docs
        run: |
          export DEBUG=vitepress:* 
          npm run docs:build || {
            echo "Build failed. Checking for missing files..."
            for file in $(find . -name "*.md"); do
              echo "Checking links in $file"
              grep -o '\[.*\]([^)]*)' "$file" || true
            done
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 